### ISSUE TITLE
Keep the original file names after unpacking archive 

### ISSUE THREAD

**Issue by hcymerys** [kestra-io/plugin-compress#67]
### Feature description

Files are accessible via `outputs.<task_id>.files['path/to/original/file']` but in the storage they are renamed into names like 6651596508773726158.tmp , screenshot attached: 

![image](https://github.com/kestra-io/plugin-compress/assets/82585882/56bfb604-ba6f-4f6c-83f3-23e4c67a2834)

That cause some problems while trying to execute binaries with dynamically linked libraries (executable seek for exact name of linked library)

**Comment by loicmathieu** [comment]
Hi @hcymerys ,
We will need a flow YAML example to better understand where is the issue.
